# Generated by Django 6.0.4 on 2026-07-14 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discord-Server',
                'verbose_name_plural': 'Discord-Server',
                'ordering': ['name'],
                'permissions': [('manage_discord_bot', 'Discord-Bot verwalten')],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('match_result', 'Match-Ergebnisse'), ('news_published', 'Neue News-Artikel'), ('stream_live', 'Stream-Start'), ('manual', 'Manuell')], max_length=30)),
                ('channel_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_announcements', to=settings.AUTH_USER_MODEL)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discord_bot.discordguild')),
            ],
            options={
                'verbose_name': 'Discord-Ankündigung',
                'verbose_name_plural': 'Discord-Ankündigungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementChannelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('match_result', 'Match-Ergebnisse'), ('news_published', 'Neue News-Artikel'), ('stream_live', 'Stream-Start')], max_length=30)),
                ('channel_id', models.CharField(max_length=32)),
                ('channel_label', models.CharField(blank=True, max_length=100)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='discord_bot.discordguild')),
            ],
            options={
                'verbose_name': 'Ankündigungs-Kanal',
                'verbose_name_plural': 'Ankündigungs-Kanäle',
                'unique_together': {('guild', 'event_type')},
            },
        ),
    ]
