# Generated by Django 6.0.4 on 2026-07-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleAcceptanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_channel_id', models.CharField(max_length=32)),
                ('message_id', models.CharField(max_length=32)),
                ('emoji', models.CharField(default='✅', max_length=16)),
                ('role_id', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_role', to='discord_bot.discordguild')),
            ],
            options={
                'verbose_name': 'Regel-Akzeptanz',
                'verbose_name_plural': 'Regel-Akzeptanz',
            },
        ),
        migrations.CreateModel(
            name='VoiceChannelTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_channel_id', models.CharField(max_length=32)),
                ('category_id', models.CharField(help_text='Kategorie, in der die neuen Kanäle entstehen.', max_length=32)),
                ('name_prefix', models.CharField(default='Voice', max_length=50)),
                ('user_limit', models.PositiveSmallIntegerField(blank=True, help_text='Leer = kein Limit.', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Nur der Ersteller sieht/betritt den Kanal.')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_triggers', to='discord_bot.discordguild')),
            ],
            options={
                'verbose_name': 'Sprachkanal-Trigger',
                'verbose_name_plural': 'Sprachkanal-Trigger',
                'unique_together': {('guild', 'trigger_channel_id')},
            },
        ),
    ]
