# Generated by Django 6.0.4 on 2026-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0005_delete_ruleacceptanceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionrole',
            name='emoji',
            field=models.CharField(default='✅', max_length=32),
        ),
    ]
