# Generated by Django 6.0.4 on 2026-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0006_alter_reactionrole_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementchannelmapping',
            name='event_type',
            field=models.CharField(choices=[('match_result', 'Match-Ergebnisse'), ('news_published', 'Neue News-Artikel'), ('stream_live', 'Stream-Start'), ('pracc_created', 'Neuer Pracc geplant')], max_length=30),
        ),
        migrations.AlterField(
            model_name='announcementlog',
            name='event_type',
            field=models.CharField(choices=[('match_result', 'Match-Ergebnisse'), ('news_published', 'Neue News-Artikel'), ('stream_live', 'Stream-Start'), ('pracc_created', 'Neuer Pracc geplant'), ('manual', 'Manuell')], max_length=30),
        ),
    ]
