# Generated by Django 6.0.4 on 2026-07-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSocialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20)),
                ('follower_count', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('auto', 'Automatisch synchronisiert'), ('manual', 'Manuell gepflegt')], default='manual', max_length=10)),
                ('stats_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spieler-Social-Media-Statistik',
                'verbose_name_plural': 'Spieler-Social-Media-Statistiken',
                'constraints': [models.UniqueConstraint(fields=('user', 'platform'), name='unique_player_platform_stats')],
            },
        ),
    ]
