# Generated by Django 6.0.4 on 2026-07-12 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0001_initial'),
        ('sponsors', '0003_sociallink_data_source_sociallink_follower_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_user_id', models.CharField(max_length=64)),
                ('twitch_login', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitch_authorization', to='sponsors.sociallink')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitch_authorization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twitch-Autorisierung',
                'verbose_name_plural': 'Twitch-Autorisierungen',
            },
        ),
    ]
