# Generated by Django 6.0.4 on 2026-07-12 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0002_twitchauthorization'),
        ('sponsors', '0003_sociallink_data_source_sociallink_follower_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20)),
                ('follower_count', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('social_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sponsors.sociallink')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_stats_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social-Media-Reichweiten-Snapshot',
                'verbose_name_plural': 'Social-Media-Reichweiten-Snapshots',
                'indexes': [models.Index(fields=['user', 'platform', 'recorded_at'], name='social_stat_user_id_2b26ac_idx'), models.Index(fields=['social_link', 'platform', 'recorded_at'], name='social_stat_social__cfe65a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwitchViewerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_count', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('social_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_snapshots', to='sponsors.sociallink')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitch_viewer_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twitch-Zuschauer-Snapshot',
                'verbose_name_plural': 'Twitch-Zuschauer-Snapshots',
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='social_stat_user_id_36343c_idx'), models.Index(fields=['social_link', 'recorded_at'], name='social_stat_social__a1c4be_idx')],
            },
        ),
    ]
