# Generated by Django 6.0.4 on 2026-07-13 07:59

import social_stats.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0005_encrypt_existing_twitch_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchauthorization',
            name='access_token',
            field=social_stats.crypto.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='twitchauthorization',
            name='refresh_token',
            field=social_stats.crypto.EncryptedTextField(),
        ),
    ]
