# Generated by Django 6.0.4 on 2026-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['order', 'name'], 'permissions': [('manage_sponsors', 'Kann Sponsoren & Social Links verwalten')], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsoren'},
        ),
    ]
