# Generated by Django 6.0.4 on 2026-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='data_source',
            field=models.CharField(choices=[('auto', 'Automatisch synchronisiert'), ('manual', 'Manuell gepflegt')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='follower_count',
            field=models.PositiveIntegerField(blank=True, help_text='Follower/Abonnenten/Mitglieder, je nach Plattform.', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='stats_updated_at',
            field=models.DateTimeField(blank=True, help_text='Letzte automatische Synchronisation oder manuelle Pflege der Reichweiten-Zahlen.', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, help_text='Gesamt-Views, falls von der Plattform bereitgestellt (z.B. YouTube).', null=True),
        ),
    ]
