# Generated by Django 6.0.4 on 2026-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_sociallink_data_source_sociallink_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='impressions_count',
            field=models.PositiveIntegerField(blank=True, help_text='Anzahl Anzeigen des Inhalts, inkl. Mehrfachansichten.', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='reach_count',
            field=models.PositiveIntegerField(blank=True, help_text='Anzahl erreichter Accounts/Personen.', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='share_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
