# Generated by Django 6.0.4 on 2026-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_sociallink_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('discord', 'Discord'), ('tiktok', 'TikTok'), ('other', 'Sonstiges')], max_length=20),
        ),
    ]
