# Generated by Django 6.0.4 on 2026-08-19 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_alias', models.CharField(help_text="z.B. 'info', 'orga', 'self'.", max_length=50)),
                ('from_address', models.EmailField(max_length=254)),
                ('to', models.TextField(help_text='Kommagetrennte Empfängerliste, wie eingegeben.')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_by_username', models.CharField(blank=True, help_text='Snapshot des Benutzernamens - bleibt auch erhalten, wenn der Account später gelöscht wird.', max_length=150, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gesendete E-Mail',
                'verbose_name_plural': 'Gesendete E-Mails',
                'ordering': ['-created_at'],
                'permissions': [('send_email', 'Kann Freitext-E-Mails über das Dashboard versenden')],
            },
        ),
    ]
