# Generated by Django 6.0.4 on 2026-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('news', 'News'), ('teams', 'Teams'), ('about_us', 'Über uns'), ('sponsors', 'Sponsoren'), ('contact', 'Kontakt'), ('join_us', 'Join Us'), ('privacy', 'Datenschutz'), ('imprint', 'Impressum'), ('creators', 'Creators')], max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/page_backgrounds/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seiten-Hintergrundbild',
                'verbose_name_plural': 'Seiten-Hintergrundbilder',
                'ordering': ['page_key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Seiteneinstellungen',
                'verbose_name_plural': 'Seiteneinstellungen',
                'permissions': [('manage_site_settings', 'Kann Hero-Video & Seiten-Hintergründe verwalten')],
            },
        ),
    ]
