"""
Django settings for punishers_ger project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env (see .env.example). Real
# secrets and per-environment config (dev vs. production) live there instead
# of being hardcoded, so .env is gitignored and .env.example documents it.
load_dotenv(BASE_DIR / '.env')


def _env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def _env_list(name: str, default: str) -> list[str]:
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dz8*r6*h(j%5ex5^bkd0r)@jyv0rg58izu9#w9x$^5#gs4*i05",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")

# --- FastAPI layer configuration (read by fastapi_app/main.py via
# django.conf.settings, so Django and FastAPI share one source of truth) ---

# Public base URL the FastAPI app is reachable at; used to build absolute
# media URLs (profile pictures, news images, ...) returned to the frontend.
BACKEND_BASE_URL = os.environ.get("BACKEND_BASE_URL", "http://localhost:8000")

# Public base URL of the frontend SPA; used to redirect the browser back
# after third-party OAuth flows (see social_stats/ Twitch connect).
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173")

# Origins allowed to call the FastAPI API directly from the browser.
CORS_ORIGINS = _env_list(
    "CORS_ORIGINS", "http://localhost:5173,http://localhost:3000"
)

# JWT auth. JWT_SECRET_KEY defaults to SECRET_KEY if unset, but should be set
# independently in production so rotating one doesn't invalidate the other.
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY", SECRET_KEY)
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.environ.get("JWT_ACCESS_TOKEN_EXPIRE_MINUTES", "60"))
JWT_REFRESH_TOKEN_EXPIRE_DAYS = int(os.environ.get("JWT_REFRESH_TOKEN_EXPIRE_DAYS", "30"))

# Password-reset links (see users/emails.py) expire after this long.
PASSWORD_RESET_TOKEN_EXPIRE_MINUTES = int(os.environ.get("PASSWORD_RESET_TOKEN_EXPIRE_MINUTES", "30"))

# Transactional email (account-activated / password-reset notifications, see
# users/emails.py). No EMAIL_HOST configured -> falls back to Django's
# console backend, which just prints the email to the server log - same
# graceful-degradation approach as the missing-credentials handling for
# Twitch/YouTube, so local dev works with zero setup. Any free SMTP provider
# (a Gmail account with an App Password, Brevo's free tier, ...) works here,
# since the org has no paid mail service yet.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Punishers Germany <no-reply@punishers.gg>")
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST
    else "django.core.mail.backends.console.EmailBackend"
)

# FACEIT Data API v4 (see faceit_integration/). Server-side API key from
# https://developers.faceit.com/ - required for any sync to actually run.
FACEIT_API_KEY = os.environ.get("FACEIT_API_KEY") or None
FACEIT_DEFAULT_GAME_ID = os.environ.get("FACEIT_DEFAULT_GAME_ID", "cs2")
# In-process scheduler interval for automatic syncing; set to "0" to disable
# the background scheduler entirely (e.g. if you only want cron/manual runs).
FACEIT_SYNC_INTERVAL_MINUTES = int(os.environ.get("FACEIT_SYNC_INTERVAL_MINUTES", "360"))

# Twitch Helix API (see twitch_integration/client.py) - app registered at
# https://dev.twitch.tv/console. Used only for public live-stream status of
# our own registered content creators, no user-specific scopes needed.
TWITCH_CLIENT_ID = os.environ.get("TWITCH_CLIENT_ID") or None
TWITCH_CLIENT_SECRET = os.environ.get("TWITCH_CLIENT_SECRET") or None

# Social-media reach stats (see social_stats/). YouTube Data API v3 key from
# https://console.cloud.google.com/apis/credentials - public read-only, no
# per-channel OAuth needed. Discord's invite-based member count needs no key
# at all (see social_stats/discord_client.py).
YOUTUBE_API_KEY = os.environ.get("YOUTUBE_API_KEY") or None
SOCIAL_STATS_SYNC_INTERVAL_MINUTES = int(os.environ.get("SOCIAL_STATS_SYNC_INTERVAL_MINUTES", "360"))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'teams',
    'leagues',
    'news',
    'sponsors',
    'faceit_integration',
    'audit_log',
    'social_stats',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'punishers_ger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'punishers_ger.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de-DE'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Optional: for collecting static files in production

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Note: CORS and the public/admin API are handled entirely by the FastAPI
# app (fastapi_app/main.py), which is the only HTTP API surface for the
# frontend. Django itself is only used for the ORM/models and /admin/.
