# Generated by Django 6.0.4 on 2026-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaVaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_url', models.URLField(blank=True, help_text='z.B. https://vault.punishersgermany.de/')),
            ],
            options={
                'verbose_name': 'Social-Media-Vault-Einstellungen',
                'verbose_name_plural': 'Social-Media-Vault-Einstellungen',
                'permissions': [('manage_social_media_vault', 'Social-Media-Zugangsdaten verwalten (Vaultwarden)')],
            },
        ),
    ]
