# Generated by Django 6.0.4 on 2026-07-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, help_text='Snapshot des Benutzernamens zum Zeitpunkt der Aktion - bleibt auch erhalten, wenn der Account später gelöscht wird.', max_length=150, null=True)),
                ('action', models.CharField(help_text="z.B. 'create', 'update', 'delete', 'activate', 'role_assign'.", max_length=50)),
                ('resource_type', models.CharField(help_text="z.B. 'NewsArticle', 'Team', 'Sponsor', 'CustomUser', 'Group'.", max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=64, null=True)),
                ('resource_label', models.CharField(blank=True, help_text='Menschenlesbarer Bezug, z.B. Artikel-Titel oder Team-Name.', max_length=255, null=True)),
                ('details', models.JSONField(blank=True, help_text='Zusätzlicher Kontext, z.B. geänderte Felder oder zugewiesene Rollen/Rechte.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit-Log-Eintrag',
                'verbose_name_plural': 'Audit-Log-Einträge',
                'ordering': ['-created_at'],
            },
        ),
    ]
