# Generated by Django 6.0.4 on 2026-07-14 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingame_name', models.CharField(max_length=100)),
                ('game', models.CharField(choices=[('Counter-Strike 2', 'Counter-Strike 2'), ('Valorant', 'Valorant'), ('League of Legends', 'League of Legends'), ('Rocket League', 'Rocket League'), ('Rainbow Six Siege', 'Rainbow Six Siege')], max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('discord_tag', models.CharField(blank=True, max_length=50)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spieler-Bewerbung',
                'verbose_name_plural': 'Spieler-Bewerbungen',
                'ordering': ['-created_at'],
                'permissions': [('manage_applications', 'Bewerbungen einsehen & bearbeiten (alle Spiele)')],
            },
        ),
    ]
