# Generated by Django 6.0.4 on 2026-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HetznerVPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hetzner_server_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_known_status', models.CharField(choices=[('unknown', 'Unbekannt'), ('running', 'Läuft'), ('off', 'Ausgeschaltet'), ('starting', 'Startet'), ('stopping', 'Fährt herunter')], default='unknown', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hetzner-VPS',
                'verbose_name_plural': 'Hetzner-VPS',
                'permissions': [('manage_gameservers', 'CS2-Gameserver verwalten')],
            },
        ),
    ]
