# Generated by Django 6.0.4 on 2026-07-19 13:41

import django.db.models.deletion
import social_stats.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='z.B. "Pracc-Server 1" oder "Util-Server".', max_length=100)),
                ('kind', models.CharField(choices=[('pracc', 'Pracc'), ('util', 'Util')], max_length=10)),
                ('docker_container_name', models.CharField(blank=True, max_length=64, unique=True)),
                ('port', models.PositiveIntegerField(help_text='UDP-Port für Spielverkehr - RCON läuft über TCP auf demselben Port (Source-Engine-Konvention).')),
                ('rcon_password', social_stats.crypto.EncryptedTextField()),
                ('last_known_status', models.CharField(choices=[('unknown', 'Unbekannt'), ('creating', 'Wird erstellt'), ('running', 'Läuft'), ('stopped', 'Gestoppt'), ('starting', 'Startet'), ('stopping', 'Stoppt')], default='unknown', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='gameservers.hetznervps')),
            ],
            options={
                'verbose_name': 'CS2-Server-Slot',
                'verbose_name_plural': 'CS2-Server-Slots',
                'ordering': ['vps', 'label'],
            },
        ),
    ]
