# Generated by Django 6.0.4 on 2026-07-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0002_serverslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='z.B. "Standard Pracc" oder "Active Duty Map-Pool".', max_length=100)),
                ('kind', models.CharField(choices=[('pracc', 'Pracc'), ('util', 'Util'), ('map_pool', 'Map-Pool')], max_length=10)),
                ('file', models.FileField(upload_to='gameserver_configs/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Server-Config',
                'verbose_name_plural': 'Server-Configs',
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.AddField(
            model_name='serverslot',
            name='current_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_on_slots', to='gameservers.serverconfig'),
        ),
    ]
