# Generated by Django 6.0.4 on 2026-07-19 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0003_serverconfig_serverslot_current_config'),
        ('teams', '0005_alter_player_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_team_name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Geplant'), ('live', 'Live'), ('finished', 'Beendet'), ('cancelled', 'Abgesagt')], default='scheduled', max_length=10)),
                ('demo_file', models.FileField(blank=True, null=True, upload_to='gameserver_demos/')),
                ('match_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_praccs', to=settings.AUTH_USER_MODEL)),
                ('own_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praccs', to='teams.team')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praccs', to='gameservers.serverslot')),
            ],
            options={
                'verbose_name': 'Pracc',
                'verbose_name_plural': 'Praccs',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
