# Generated by Django 6.0.4 on 2026-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0004_pracc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracc',
            name='demo_file',
        ),
        migrations.AddField(
            model_name='pracc',
            name='demo_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pracc',
            name='demo_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
