# Generated by Django 6.0.4 on 2026-07-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0005_remove_pracc_demo_file_pracc_demo_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracc',
            name='map_pool_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='praccs_using_pool', to='gameservers.serverconfig'),
        ),
    ]
