# Generated by Django 6.0.4 on 2026-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='faceit_championship_id',
            field=models.CharField(blank=True, help_text='FACEIT championship/competition ID (Data API v4), z.B. für ESEA oder DACH CS getrennt. Nötig, um Matches dieser Liga abzurufen.', max_length=64, null=True, unique=True),
        ),
    ]
