# Generated by Django 6.0.4 on 2026-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_faceit_championship_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='faceit_championship_id',
        ),
        migrations.AddField(
            model_name='league',
            name='faceit_organizer_id',
            field=models.CharField(blank=True, help_text='FACEIT Organizer ID (Data API v4), z.B. für ESEA oder DACH CS getrennt. Ablesbar aus der Organizer-URL: faceit.com/de/organizers/<diese-id>/<name>. Daraus werden die Championships (Seasons) und darüber die Matches abgerufen.', max_length=64, null=True, unique=True),
        ),
    ]
