# Generated by Django 6.0.4 on 2026-07-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_faceit_championship_id'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faceit_player_id',
            field=models.CharField(blank=True, help_text='FACEIT Player ID (Data API v4), z.B. aus der FACEIT-Profil-URL ableitbar.', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TeamLeagueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceit_team_id', models.CharField(blank=True, help_text='FACEIT Team ID as registered for this specific league/championship.', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='leagues.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_entries', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team-Liga-Zuordnung',
                'verbose_name_plural': 'Team-Liga-Zuordnungen',
                'ordering': ['team__name', 'league__name'],
                'unique_together': {('team', 'league')},
            },
        ),
    ]
