# Generated by Django 6.0.4 on 2026-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_player_faceit_player_id_teamleagueentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['game', 'name'], 'permissions': [('manage_teams', 'Kann alle Teams & Spieler verwalten (nicht nur das eigene Team)')], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
