# Generated by Django 6.0.4 on 2026-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='show_extended_profile',
            field=models.BooleanField(default=False, help_text='Zeigt Bio und Social-Links auf dem öffentlichen Spielerprofil (sonst nur Bild, Name, Rolle, Team).'),
        ),
    ]
