# Generated by Django 6.0.4 on 2026-08-31 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0006_player_show_extended_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('announcement', 'Ankündigung (bevorstehendes Match)'), ('result', 'Ergebnis')], max_length=20)),
                ('opponent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('competition_name', models.CharField(blank=True, max_length=200, null=True)),
                ('match_datetime', models.DateTimeField(blank=True, null=True)),
                ('team_maps_won', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opponent_maps_won', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maps_summary', models.CharField(blank=True, help_text="z.B. 'de_mirage 13:7, de_inferno 10:16, de_ancient 16:12' - für den KI-Prompt und die Anzeige.", max_length=300, null=True)),
                ('text_facebook', models.TextField(blank=True)),
                ('text_instagram', models.TextField(blank=True)),
                ('text_x', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_posts/')),
                ('generation_error', models.TextField(blank=True, help_text='Gesetzt, wenn Text- und/oder Bild-Generierung fehlgeschlagen ist (z.B. Ollama nicht erreichbar) - der Entwurf existiert trotzdem, ggf. nur teilweise befüllt.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_drafts', to='teams.team')),
            ],
            options={
                'verbose_name': 'Social-Media-Post-Entwurf',
                'verbose_name_plural': 'Social-Media-Post-Entwürfe',
                'ordering': ['-created_at'],
            },
        ),
    ]
