# Generated by Django 6.0.4 on 2026-08-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialpostdraft',
            options={'ordering': ['-created_at'], 'permissions': [('manage_social_posts', 'Kann Social-Media-Post-Entwürfe einsehen/verwalten')], 'verbose_name': 'Social-Media-Post-Entwurf', 'verbose_name_plural': 'Social-Media-Post-Entwürfe'},
        ),
    ]
