# Generated by Django 6.0.4 on 2026-08-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_posts', '0002_alter_socialpostdraft_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostdraft',
            name='opponent_logo_url',
            field=models.URLField(blank=True, help_text='FACEIT-Team-Avatar des Gegners (nur bei synchronisierten Matches vorhanden, nicht bei manuell erfassten) - fürs Bild-Template.', max_length=500, null=True),
        ),
    ]
