# Generated by Django 6.0.4 on 2026-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_posts', '0003_socialpostdraft_opponent_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostdraft',
            name='maps',
            field=models.JSONField(blank=True, help_text="Strukturierte Maps-Liste fürs Bild-Template (Maps-Zeile), z.B. [{'name': 'de_mirage', 'team_score': 13, 'opponent_score': 7, 'result': 'win'}, ...]. Separat von maps_summary (Freitext für den KI-Prompt) gehalten - siehe generation.py.", null=True),
        ),
    ]
