# Generated by Django 6.0.4 on 2026-07-10 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Titelbild')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Veröffentlichungsdatum')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Zuletzt aktualisiert')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'News Artikel',
                'verbose_name_plural': 'News Artikel',
                'ordering': ['-published_date'],
            },
        ),
    ]
