# Generated by Django 6.0.4 on 2026-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date'], 'permissions': [('manage_news', 'Kann News-Artikel verwalten (erstellen/bearbeiten/löschen)')], 'verbose_name': 'News Artikel', 'verbose_name_plural': 'News Artikel'},
        ),
    ]
