# Generated by Django 6.0.4 on 2026-07-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='original_language',
            field=models.CharField(default='de', max_length=5, verbose_name='Originalsprache'),
        ),
        migrations.CreateModel(
            name='NewsArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_machine_translated', models.BooleanField(default=True)),
                ('translated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.newsarticle')),
            ],
            options={
                'verbose_name': 'News-Artikel-Übersetzung',
                'verbose_name_plural': 'News-Artikel-Übersetzungen',
                'unique_together': {('article', 'language')},
            },
        ),
    ]
