# Generated by Django 6.0.4 on 2026-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_system_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='creator_bio',
            field=models.TextField(blank=True, help_text='Kurzbeschreibung für die Creators-Seite.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_content_creator',
            field=models.BooleanField(default=False, help_text='Auf der /creators-Seite anzeigen?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_featured_creator',
            field=models.BooleanField(default=False, help_text="Nur relevant, wenn is_content_creator gesetzt ist: größere Karte in der 'Featured'-Sektion."),
        ),
    ]
