# Generated by Django 6.0.4 on 2026-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_creator_bio_customuser_is_content_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_users', 'Kann Nutzer aktivieren/deaktivieren')]},
        ),
    ]
