# Generated by Django 6.0.4 on 2026-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_author_gets_manage_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
