# Generated by Django 6.0.4 on 2026-07-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_instagram_link_customuser_tiktok_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_known_live',
            field=models.BooleanField(default=False),
        ),
    ]
