# Generated by Django 6.0.4 on 2026-07-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_last_known_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der ersten Freischaltung - null bedeutet, das Konto wurde noch nie aktiviert (frische Registrierung).', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-gelöscht - aus der Admin-Liste ausgeblendet und deaktiviert, Daten bleiben aber erhalten.'),
        ),
    ]
