# Generated by Django 6.0.4 on 2026-07-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_activated_at_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='game_profile_link',
            field=models.URLField(blank=True, help_text='Link zu einer Stats-/Tracker-Seite fürs jeweilige Spiel, z.B. Steam-Community-Profil (CS2), tracker.gg (Valorant), op.gg (LoL) oder ballchasing.com (Rocket League).', null=True),
        ),
    ]
