# Generated by Django 6.0.4 on 2026-07-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_player_faceit_player_id_teamleagueentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceitSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Automatisch'), ('manual', 'Manuell'), ('command', 'CLI-Befehl')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('players_synced', models.PositiveIntegerField(default=0)),
                ('players_failed', models.PositiveIntegerField(default=0)),
                ('matches_synced', models.PositiveIntegerField(default=0)),
                ('league_entries_failed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, help_text='Gesetzt, wenn der gesamte Lauf fehlgeschlagen ist (z.B. fehlender API-Key).', null=True)),
            ],
            options={
                'verbose_name': 'FACEIT Sync-Lauf',
                'verbose_name_plural': 'FACEIT Sync-Läufe',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerFaceitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(default='cs2', help_text="FACEIT game ID, z.B. 'cs2'.", max_length=32)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('faceit_elo', models.PositiveIntegerField(blank=True, null=True)),
                ('matches', models.PositiveIntegerField(blank=True, null=True)),
                ('win_rate_percent', models.FloatField(blank=True, null=True)),
                ('avg_kd_ratio', models.FloatField(blank=True, null=True)),
                ('avg_headshots_percent', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Vollständige zuletzt abgerufene FACEIT-API-Antwort, für spätere Auswertungen.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faceit_stats', to='teams.player')),
            ],
            options={
                'verbose_name': 'FACEIT Spieler-Statistik',
                'verbose_name_plural': 'FACEIT Spieler-Statistiken',
            },
        ),
        migrations.CreateModel(
            name='TeamFaceitMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceit_match_id', models.CharField(max_length=64, unique=True)),
                ('competition_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Bevorstehend'), ('ongoing', 'Laufend'), ('finished', 'Beendet'), ('cancelled', 'Abgesagt')], default='upcoming', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('opponent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('opponent_score', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('win', 'Sieg'), ('loss', 'Niederlage'), ('draw', 'Unentschieden')], max_length=10, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('league_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.teamleagueentry')),
            ],
            options={
                'verbose_name': 'FACEIT Match',
                'verbose_name_plural': 'FACEIT Matches',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
