# Generated by Django 6.0.4 on 2026-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfaceitmatch',
            name='map_name',
            field=models.CharField(blank=True, help_text="Gespielte Map, falls von FACEIT verfügbar (z.B. 'de_mirage'). Basis für die Team-Map-Statistiken.", max_length=100, null=True),
        ),
    ]
