# Generated by Django 6.0.4 on 2026-07-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_integration', '0002_teamfaceitmatch_map_name'),
        ('teams', '0003_player_faceit_player_id_teamleagueentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceitsyncrun',
            name='player_match_stats_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceitsyncrun',
            name='player_match_stats_synced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(blank=True, null=True)),
                ('deaths', models.PositiveIntegerField(blank=True, null=True)),
                ('assists', models.PositiveIntegerField(blank=True, null=True)),
                ('kd_ratio', models.FloatField(blank=True, null=True)),
                ('kr_ratio', models.FloatField(blank=True, null=True)),
                ('headshots', models.PositiveIntegerField(blank=True, null=True)),
                ('headshots_percent', models.FloatField(blank=True, null=True)),
                ('mvps', models.PositiveIntegerField(blank=True, null=True)),
                ('triple_kills', models.PositiveIntegerField(blank=True, null=True)),
                ('quadro_kills', models.PositiveIntegerField(blank=True, null=True)),
                ('penta_kills', models.PositiveIntegerField(blank=True, null=True)),
                ('utility_damage', models.FloatField(blank=True, null=True)),
                ('utility_successes', models.PositiveIntegerField(blank=True, null=True)),
                ('utility_count', models.PositiveIntegerField(blank=True, null=True)),
                ('flash_count', models.PositiveIntegerField(blank=True, null=True)),
                ('flash_successes', models.PositiveIntegerField(blank=True, null=True)),
                ('enemies_flashed', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_count', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_wins', models.PositiveIntegerField(blank=True, null=True)),
                ('clutch_1v1_count', models.PositiveIntegerField(blank=True, null=True)),
                ('clutch_1v1_wins', models.PositiveIntegerField(blank=True, null=True)),
                ('clutch_1v2_count', models.PositiveIntegerField(blank=True, null=True)),
                ('clutch_1v2_wins', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('win', 'Sieg'), ('loss', 'Niederlage'), ('draw', 'Unentschieden')], max_length=10, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Rohe player_stats + Runden-Kontext von FACEIT für dieses Match.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='faceit_integration.teamfaceitmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='teams.player')),
            ],
            options={
                'verbose_name': 'FACEIT Spieler-Match-Statistik',
                'verbose_name_plural': 'FACEIT Spieler-Match-Statistiken',
                'ordering': ['-match__finished_at'],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
