# Generated by Django 6.0.4 on 2026-07-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_integration', '0003_faceitsyncrun_player_match_stats_failed_and_more'),
        ('teams', '0004_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermatchstats',
            options={'verbose_name': 'FACEIT Spieler-Match-Statistik', 'verbose_name_plural': 'FACEIT Spieler-Match-Statistiken'},
        ),
        migrations.AddField(
            model_name='faceitsyncrun',
            name='solo_match_stats_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceitsyncrun',
            name='solo_match_stats_synced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceitsyncrun',
            name='solo_matches_synced',
            field=models.PositiveIntegerField(default=0, help_text='Solo-Matches teamloser Spieler (siehe PlayerFaceitMatch).'),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='faceit_integration.teamfaceitmatch'),
        ),
        migrations.CreateModel(
            name='PlayerFaceitMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceit_match_id', models.CharField(max_length=64)),
                ('competition_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Bevorstehend'), ('ongoing', 'Laufend'), ('finished', 'Beendet'), ('cancelled', 'Abgesagt')], default='upcoming', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('opponent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('player_score', models.PositiveIntegerField(blank=True, null=True)),
                ('opponent_score', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('win', 'Sieg'), ('loss', 'Niederlage'), ('draw', 'Unentschieden')], max_length=10, null=True)),
                ('map_name', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_matches', to='teams.player')),
            ],
            options={
                'verbose_name': 'FACEIT Solo-Match',
                'verbose_name_plural': 'FACEIT Solo-Matches',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='solo_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='faceit_integration.playerfaceitmatch'),
        ),
        migrations.AddConstraint(
            model_name='playermatchstats',
            constraint=models.CheckConstraint(condition=models.Q(('match__isnull', False), ('solo_match__isnull', False), _connector='XOR'), name='playermatchstats_exactly_one_match_source'),
        ),
        migrations.AddConstraint(
            model_name='playermatchstats',
            constraint=models.UniqueConstraint(fields=('player', 'solo_match'), name='uniq_player_solo_match'),
        ),
        migrations.AlterUniqueTogether(
            name='playerfaceitmatch',
            unique_together={('player', 'faceit_match_id')},
        ),
    ]
