# Generated by Django 6.0.4 on 2026-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_integration', '0004_alter_playermatchstats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfaceitmatch',
            name='series_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
